require("helder.plugins-setup")
require("helder.core.options")
require("helder.core.colorscheme")
require("helder.core.keymaps")
require("helder.plugins.comment")
require("helder.plugins.nvim-tree")
require("helder.plugins.telescope-setup")
require("helder.plugins.nvim-cmp")
require("helder.plugins.lsp.mason")
require("helder.plugins.lsp.lspsaga")
require("helder.plugins.lsp.lspconfig")
require("helder.plugins.lsp.null-ls")
require("helder.plugins.autopairs")
require("helder.plugins.treesitter")
require("helder.plugins.gitsigns")

vim.lsp.set_log_level("debug")
